project:
  type: website
  # Remove folder if Quarto needs to re-render due to change
  render: 
    - "*.qmd"
    # - "!template.qmd"
    # - "!DataScience/"
    # - "!Foundations/"
    # - "!SpecialTopics/"

website:
  title: "R for Lifestyle and Brain Health (R-LAB)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: introduction.qmd
        text: R Basics
      - href: presentations.qmd
        text: Presentations

format:
  html:
    theme:
      - lumen
    css: styles.css

execute: 
  freeze: auto



