---
title: "2026 Attendees"
---

### [Jackie Adedokun](https://bhelsel.github.io/2026-RLAB-Practical-Exercises/attendees/JackieAdedokun/about.html)

Jackie is a Research Specialist with the Department of Psychiatry at the
University of Pittsburgh.

### [Abass Babatunde](https://bhelsel.github.io/2026-RLAB-Practical-Exercises/attendees/AbassBabatunde/about.html)

Abassis a Postdoctoral Fellow with the Institute for the Advancement of
Community Health at Furman University.

### [Ashlyn Barry](https://bhelsel.github.io/2026-RLAB-Practical-Exercises/attendees/AshlynBarry/about.html)

Ashlyn is a Graduate Student with the Department of Kinesiology at the
University of Wisconsin - Madison.

### [Morgan Brucks](https://bhelsel.github.io/2026-RLAB-Practical-Exercises/attendees/MorganBrucks/about.html)

Morgan is a Senior Research Associate with the Department of Population Health
at the University of Kansas Medical Center.

### [Wasayef Bsharat](https://bhelsel.github.io/2026-RLAB-Practical-Exercises/attendees/WasayefBsharat/about.html)

Wasayef is a Graduate Student with the Department of Clinical Psychology at
Montclair State University.

### [Julianne Clina](https://bhelsel.github.io/2026-RLAB-Practical-Exercises/attendees/JulianneClina/about.html)

Julianne is a Postdoctoral Fellow with the Division of Physical Activity and
Weight Mangagement in the Department of Internal Medicine at the University of
Kansas Medical Center.                                    

### [Kellie Collins](https://bhelsel.github.io/2026-RLAB-Practical-Exercises/attendees/KellieCollins/about.html)

Kellie is a Graduate Student in Clinical Investigation with the Department of
Pediatrics at the University of Wisconsin - Madison.
  
### [Bethany Forseth](https://bhelsel.github.io/2026-RLAB-Practical-Exercises/attendees/BethanyForseth/about.html)

Bethany is an Assistant Professor with the Department of Physical Therapy,
Rehabilitation Science, and Athletic Training at the University of Kansas
Medical Center.
 
### [Sara Fortin-Miller](https://bhelsel.github.io/2026-RLAB-Practical-Exercises/attendees/SaraFortinMiller/about.html)

Sara is a Postdoctoral Fellow with the Department of Population Health at the
University of Kansas Medical Center.

### [Elham Ghanbarian](https://bhelsel.github.io/2026-RLAB-Practical-Exercises/attendees/ElhamGhanbarian/about.html)

Elham is a Postdoctoral Fellow with the Department of Neurology at the
University of California, Irvine.

### [Rachel Hantman](https://bhelsel.github.io/2026-RLAB-Practical-Exercises/attendees/RachelHantman/about.html)

Rachel is a Graduate Student with the Department of Psychology at the University
of South Carolina.

### [John Heap](https://bhelsel.github.io/2026-RLAB-Practical-Exercises/attendees/JohnHeap/about.html)

John is a Graduate Student with the School of Medicine at the University of
Kansas Medical Center.

### [Brian Helsel](https://bhelsel.github.io/2026-RLAB-Practical-Exercises/attendees/BrianHelsel/about.html)

Brian is an Assistant Professor with the University of Kansas Alzheimer's
Disease Research Center in the Department of Neurology at the University of
Kansas Medical Center.

### [Rashelle Hoffman](https://bhelsel.github.io/2026-RLAB-Practical-Exercises/attendees/RashelleHoffman/about.html)

Rashelle is an Assistant Professor with the Department of Physical Therapy at
Creighton University.

### [Dominic Javonillo](https://bhelsel.github.io/2026-RLAB-Practical-Exercises/attendees/DominicJavonillo/about.html)

Dominic is a Graduate Student with the Department of Neurobiology & Behavior at
the University of California, Irvine.

### [Melissa Jenkins](https://bhelsel.github.io/2026-RLAB-Practical-Exercises/attendees/MelissaJenkins/about.html)

Melissa is a Postdoctoral Fellow with the Waisman Center at the University of
Wisconsin - Madison.

### [Sullafa Kadura](https://bhelsel.github.io/2026-RLAB-Practical-Exercises/attendees/SullafaKadura/about.html)

Sullafa is an Associate Professor with the Departmnet of Medicine at the
University of Pittsburgh.

### [Jessica Keller](https://bhelsel.github.io/2026-RLAB-Practical-Exercises/attendees/JessicaKeller/about.html)

Jessica is a Postdoctoral Fellow with the Department of Anesthesiology at the
University of Kansas Medical Center

### [Mason McClarnon](https://bhelsel.github.io/2026-RLAB-Practical-Exercises/attendees/MasonMcClarnon/about.html)

Mason is a research assistant with the School of Pharmacy and Health Professions
at Creighton University.

### [Yasaman Razavi](https://bhelsel.github.io/2026-RLAB-Practical-Exercises/attendees/YasamanRazavi/about.html)

Yasaman is an Associate Specialist with the Department of Anesthesia at the
University of California San Francisco.

### [Sadaf Salehi](https://bhelsel.github.io/2026-RLAB-Practical-Exercises/attendees/SadafSalehi/about.html)

Sadaf is an Associate Researcher with the Multiple Sclerosis Research Center at
the Tehran University of Medical Sciences.

### [Leela Shah](https://bhelsel.github.io/2026-RLAB-Practical-Exercises/attendees/LeelaShah/about.html)

Leela is a Graduate Student with the Waisman Center at the University of
Wisconsin - Madison.

### [Kameron Suire](https://bhelsel.github.io/2026-RLAB-Practical-Exercises/attendees/KameronSuire/about.html)

Kameron is an Assistant Professor of Exercise Science with the Department of
Kinesiology at Berry College.

### [David Titus](https://bhelsel.github.io/2026-RLAB-Practical-Exercises/attendees/DavidTitus/about.html)

David is a Neuroscientist with the Department of Veterinary Clinical Sciences at
the University of Minnesota Twin Cities.

### [Ainsley VanderGiesen](https://bhelsel.github.io/2026-RLAB-Practical-Exercises/attendees/AinsleyVanderGiesen/about.html)

Ainsley is a Clinical Research Assistant with the Department of Anesthesiology
at the University of Kansas Medical Center.

### [Elyse Vetter](https://bhelsel.github.io/2026-RLAB-Practical-Exercises/attendees/ElyseVetter/about.html)

Elyse is a Graduate Student with the Department of Neurology at the University
of Kansas Medical Center.

### [Ian Weidling](https://bhelsel.github.io/2026-RLAB-Practical-Exercises/attendees/IanWeidling/about.html)

Ian is a Postdoctoral Fellow with the Department of Neurology at the University
of Kansas Medical Center.